### ISSUE TITLE
프레임워크 설정 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by kth31815** [ustraframework/ustraframework#4]
작성자 : 김태훈
연관프로젝트 : GSR 전사 통합 VOC 구축
내용 :  ustra framework 실행중 오류 발생해서 확인해 보니 다음과 같은 파일이 존재 하지 않는 것으로 확인이 되고 있어서 문의 드립니다. 

혹시 추가적으로 저희가 받아야 되는 파일이 있는지 확인차 문의를 드리게 되었습니다. 오류 내용은 아래와 같습니다.

16:13:21.654 [restartedMain] INFO  org.reflections.Reflections - Reflections took 129 ms to scan 8 urls, producing 191 keys and 508 values 
16:13:21.693 [restartedMain] WARN  org.reflections.Reflections - could not get type for name com.gsitm.ustra.java.mvc.view.web.HandlerValidationChecker from any class loader
org.reflections.ReflectionsException: could not get type for name com.gsitm.ustra.java.mvc.view.web.HandlerValidationChecker
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapper.findMappingTargetClasses(TableEntityMapper.java:99)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapper.loadTableEntityInfo(TableEntityMapper.java:37)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapper.loadTableEntityInfo(TableEntityMapper.java:122)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapperApplicationListener.onApplicationEvent(TableEntityMapperApplicationListener.java:28)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapperApplicationListener.onApplicationEvent(TableEntityMapperApplicationListener.java:11)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.gsitm.ustra.java.mvc.app.ServletApplicationRunner.run(ServletApplicationRunner.java:56)
	at com.gsretail.voc.api.ApiApplication.main(ApiApplication.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.ClassNotFoundException: com.gsitm.ustra.java.mvc.view.web.HandlerValidationChecker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:144)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
	... 28 common frames omitted
16:13:21.694 [restartedMain] WARN  org.reflections.Reflections - could not get type for name com.gsitm.ustra.java.mvc.view.web.HandlerValidationChecker from any class loader
org.reflections.ReflectionsException: could not get type for name com.gsitm.ustra.java.mvc.view.web.HandlerValidationChecker
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.reflections.Reflections.<init>(Reflections.java:168)
	at org.reflections.Reflections.<init>(Reflections.java:141)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapper.findMappingTargetClasses(TableEntityMapper.java:99)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapper.loadTableEntityInfo(TableEntityMapper.java:37)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapper.loadTableEntityInfo(TableEntityMapper.java:122)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapperApplicationListener.onApplicationEvent(TableEntityMapperApplicationListener.java:28)
	at com.gsitm.ustra.java.data.mapping.TableEntityMapperApplicationListener.onApplicationEvent(TableEntityMapperApplicationListener.java:11)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.gsitm.ustra.java.mvc.app.ServletApplicationRunner.run(ServletApplicationRunner.java:56)
	at com.gsretail.voc.api.ApiApplication.main(ApiApplication.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.ClassNotFoundException: com.gsitm.ustra.java.mvc.view.web.HandlerValidationChecker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
	... 28 common frames omitted
16:13:21.840 [restartedMain] INFO  org.reflections.Reflections - Reflections took 112 ms to scan 1 urls, producing 90 keys and 189 values 
16:13:21.897 [restartedMain] DEBUG o.s.b.a.l.ConditionEvaluationReportLoggingListener -

내용 확인 부탁 드립니다. 감사합니다.

**Comment by keymasroy** [comment]
구동 간에 문제는 없으나 내부 테이블 매핑간 클래스 로드 중 발생되는 오류였습니다.
2.0.45.2-SNAPSHOT 버전에서 개선되었으며, 프레임워크 버전을 2.0.45.2-SNAPSHOT으로 변경한 후 gradle reflesh 후 사용하시면 됩니다.

root 디렉토리 내의 build.gradle 파일 내의 "ustraVersion = '2.0.45.2-SNAPSHOT'" 으로 변경한 후 gradle refresh를 수행하시면 됩니다.
