### ISSUE TITLE
UstraExcelUtils.saveSheet 시 오류가 발생합니다.

### ISSUE THREAD

**Issue by naviarbs** [ustraframework/ustraframework#7]
화면에서 수정된 리스트를 받아 엑셀 파일로 다운로드 하는 부분입니다.

코드와 오류는 다음과 같습니다

모델의 모든 필드는 String으로 지정되어 있습니다.

```java
public void downloadExcelCustomer(@RequestBody List<BatchUploadCustomerExcelModel> in) throws Exception {
	File directory = new File("C:\\temp\\excel\\");
	if(!directory.exists()) {
		try {
			directory.mkdir();
			LOGGER.info("Directory has been created.");
		} catch(Exception e) {
			e.getStackTrace();
		}
	}
	String fileName = in.get(0).getExcelFileName();
	final FileOutputStream fos = new FileOutputStream("C:\\temp\\excel\\" + fileName + ".xlsx");

        UstraExcelUtils.saveSheet(fos, in, BatchUploadCustomerExcelModel.class);
}
```
 

 

11:16:49.062 [http-nio-9302-exec-10] DEBUG o.s.web.servlet.DispatcherServlet - POST "/api/bo/batchupload/download_excel_customer", parameters={}
11:16:49.062 [http-nio-9302-exec-10] DEBUG o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped to com.gchc.ncu.bo.batchupload.controller.BatchUploadController#downloadExcelCustomer(List)
11:16:49.063 [http-nio-9302-exec-10] DEBUG o.s.w.s.m.m.a.RequestResponseBodyMethodProcessor - Read "application/json;charset=UTF-8" to [[BatchUploadCustomerExcelModel(excelFileName=전체 목록, yr=2021, aempSexCd=null, row=45, aempNm=, aempCu (truncated)...]
11:16:49.410 [http-nio-9302-exec-10] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Using @ExceptionHandler com.gsitm.ustra.java.mvc.rest.error.RestBaseExceptionHandler#handleException(HttpServletRequest, Exception, HandlerMethod)
11:16:49.412 [http-nio-9302-exec-10] ERROR c.g.u.j.m.r.e.RestBaseExceptionHandler - java.lang.IllegalArgumentException: Can not set java.lang.String field com.gchc.ncu.bo.batchupload.models.BatchUploadCustomerExcelModel.aempNm to com.gchc.ncu.bo.batchupload.models.BatchUploadCustomerExcelModel
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.gsitm.ustra.java.data.poi.UstraExcelUtils.saveSheet(UstraExcelUtils.java:500)
	at com.gchc.ncu.bo.batchupload.controller.BatchUploadController.downloadExcelCustomer(BatchUploadController.java:307)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.gsitm.ustra.java.mvc.process.ProcessInfoLoggingFilter.doFilter(ProcessInfoLoggingFilter.java:36)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.gsitm.ustra.java.security.filter.UstraAuthenticationRequestFilter.doFilter(UstraAuthenticationRequestFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.gsitm.ustra.java.mvc.process.ProcessInfoFilter.doFilter(ProcessInfoFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.gsitm.ustra.java.mvc.filter.UstraGlobalWrapperFilter.doFilter(UstraGlobalWrapperFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by naviarbs** [comment]
문제 발생 모델은 다음과 같습니다.

```java
package com.gchc.ncu.bo.batchupload.models;


import java.util.List;
import java.util.Map;


import com.gsitm.ustra.java.data.poi.annotation.UstraExcelCellInfo;
import com.gsitm.ustra.java.management.models.base.UstraManagementBaseModel;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;


@Data
@SuperBuilder
@EqualsAndHashCode(callSuper=false)
@NoArgsConstructor
@AllArgsConstructor
public class BatchUploadCustomerExcelModel extends UstraManagementBaseModel {


	private String excelFileName; // 다운로드 엑셀 파일명


	private Integer yr;	// 기준년도
	private String aempSexCd; // 성별
	private Integer row;
	@UstraExcelCellInfo(col = 0, header = "이름", required = false) // 중복체크 로직
	private String aempNm;
	@UstraExcelCellInfo(col = 1, header = "검진등급", required = false)
	private String aempCuGrdNm;
	@UstraExcelCellInfo(col = 2, header = "백신등급", required = false)
	private String aempVcnGrdNm;
	@UstraExcelCellInfo(col = 3, header = "사번", required = false)
	private String aempId;
	@UstraExcelCellInfo(col = 4, header = "임원여부", required = false)	// Integer
	private String excuYn;
	@UstraExcelCellInfo(col = 5, header = "생년월일", required = false)	// 중복체크 로직
	private String aempBrdt;
	@UstraExcelCellInfo(col = 6, header = "입사일자", required = false)
	private String encmDt;
	@UstraExcelCellInfo(col = 7, header = "패키지명", required = false)
	private String pkgNm;
	@UstraExcelCellInfo(col = 8, header = "지원금", required = false) // Integer
	private String corpSpfn;
	@UstraExcelCellInfo(col = 9, header = "건강보험공단지원대상여부", required = false) // Integer
	private String nhicSuptTgtYn;
	@UstraExcelCellInfo(col = 10, header = "특수검진대상여부", required = false) // Integer
	private String spcuTgtYn;
	@UstraExcelCellInfo(col = 11, header = "특수물질명(1차)", required = false)
	private String extrMttrNm1;
	@UstraExcelCellInfo(col = 12, header = "특수물질명(2차)", required = false)
	private String extrMttrNm2;
	@UstraExcelCellInfo(col = 13, header = "이메일", required = false)
	private String emlAdr;
	@UstraExcelCellInfo(col = 14, header = "휴대전화번호", required = false) // 중복체크 로직
	private String mblNo;
	@UstraExcelCellInfo(col = 15, header = "배우자명", required = false)
	private String spsrNm;
	@UstraExcelCellInfo(col = 16, header = "배우자검진등급명", required = false)
	private String spsrCuGrdNm;
	@UstraExcelCellInfo(col = 17, header = "배우자백신등급명", required = false)
	private String spsrVcnGrdNm;
	@UstraExcelCellInfo(col = 18, header = "배우자회사지원금", required = false) // Integer
	private String spsrCorpSpfn;
	@UstraExcelCellInfo(col = 19, header = "배우자검진패키지", required = false)
	private String spsrPkgNm;
	@UstraExcelCellInfo(col = 20, header = "사업장", required = false)
	private String bsplNm;
	@UstraExcelCellInfo(col = 21, header = "부서1", required = false)
	private String deptNm1;
	@UstraExcelCellInfo(col = 22, header = "부서2", required = false)
	private String deptNm2;
	@UstraExcelCellInfo(col = 23, header = "부서3", required = false)
	private String deptNm3;
	@UstraExcelCellInfo(col = 24, header = "직급", required = false)
	private String jdbgNm;
	@UstraExcelCellInfo(col = 25, header = "직장전화번호", required = false)
	private String wrplTlno;
	@UstraExcelCellInfo(col = 26, header = "직장우편번호", required = false)
	private String wrplZpcd;
	@UstraExcelCellInfo(col = 27, header = "직장기본주소", required = false)
	private String wrplBscAdr;
	@UstraExcelCellInfo(col = 28, header = "직장상세주소", required = false)
	private String wrplDtlAdr;
	@UstraExcelCellInfo(col = 29, header = "자택전화번호", required = false)
	private String hsTlno;
	@UstraExcelCellInfo(col = 30, header = "자택우편번호", required = false)
	private String hsZpcd;
	@UstraExcelCellInfo(col = 31, header = "자택기본주소", required = false)
	private String hsBscAdr;
	@UstraExcelCellInfo(col = 32, header = "자택상세주소", required = false)
	private String hsDtlAdr;


	// 임직원 등록 일련번호 // Integer
	private String aempRegSeq;


	// 오류
	private List<String> error;
	private Integer errorCnt;


}
```

**Comment by keymasroy** [comment]
모델 클래스의 프로퍼티 접근 제한 이슈로 직접 접근을 제거하고 PropertyDescriptor 접근 방식으로 변경하였습니다.
"2.0.46.1-SNAPSHOT" 버전으로 업로드 되어 있는 상태입니다.

**Comment by keymasroy** [comment]
추가적으로 웹에서 컨트롤러 등을 통하여 엑셀 파일을 다운로드하는 등의 기능 구현은 아래 링크를 참고하시면 됩니다.
- 하단의 "파일 변환" 항목 참고
http://guide.ustraframework.kro.kr/ref-doc/02/6JOyC2A7aJHlk9NemSkl

**Comment by ustraframework** [comment]
해당 버그는 개선되었으므로 종료합니다.
